const baseUrl = "https://res.cloudinary.com/dq7lkkucz/image/upload/";

const ImagesAssets = {
  poster1: baseUrl + "product.png",
  Insta01: baseUrl + "Insta01.jpg",
  Insta02: baseUrl + "Insta02.jpg",
  Insta03: baseUrl + "Insta03.jpg",
  Insta04: baseUrl + "Insta04.jpg",
  Insta05: baseUrl + "Insta05.jpg",
  Insta06: baseUrl + "Insta06.jpg",
  Amazon: baseUrl + "Amazon.png",
  FlipKart: baseUrl + "FlipKart.png",
  Visa: baseUrl + "visa.png",
  PayPal: baseUrl + "PayPal.png",
  Post01: baseUrl + "Post01.jpg",
  Post02: baseUrl + "Post02.jpg",
  Post03: baseUrl + "Post03.jpg",
  Post04: baseUrl + "Post04.jpg",
  Categorie01: baseUrl + "Categorie01.png",
  Categorie02: baseUrl + "Categorie02.png",
  Categorie03: baseUrl + "Categorie03.png",
  Categorie04: baseUrl + "Categorie04.png",
  Categorie05: baseUrl + "Categorie05.png",
  Categorie06: baseUrl + "Categorie06.png",
  Selling01: baseUrl + "Selling01.png",
  Selling02: baseUrl + "Selling02.png",
  Selling03: baseUrl + "Selling03.png",
  Selling04: baseUrl + "Selling04.png",
  Selling05: baseUrl + "Selling05.png",
  Item11: baseUrl + "Item11.jpg",
  Item12: baseUrl + "Item12.jpg",
  Item13: baseUrl + "Item13.jpg",
  Item21: baseUrl + "Item21.jpg",
  Item22: baseUrl + "Item22.jpg",
  Item23: baseUrl + "Item23.jpg",
  Item31: baseUrl + "Item31.jpg",
  Item32: baseUrl + "Item32.jpg",
  Item33: baseUrl + "Item33.jpg",
  Item41: baseUrl + "Item41.jpg",
  Item42: baseUrl + "Item42.jpg",
  Item43: baseUrl + "Item43.jpg",
  Poster02: baseUrl + "Poster02.png",
};

export default ImagesAssets;
